# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "change-emitter-0.1.6" = {
      name = "change-emitter";
      packageName = "change-emitter";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/change-emitter/-/change-emitter-0.1.6.tgz";
        sha1 = "e8b2fe3d7f1ab7d69a32199aff91ea6931409515";
      };
    };
    "chrome-promise-2.2.2" = {
      name = "chrome-promise";
      packageName = "chrome-promise";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-promise/-/chrome-promise-2.2.2.tgz";
        sha512 = "2xgir3j7kcn7q8vpg82d193xzkyvaqzz6sawig9g6m1jw3jv07qam98j4pkqj3ak3fd4v4fapvm5kd0lm4dfp1g1rzpancjnj9gm55v";
      };
    };
    "core-js-1.2.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz";
        sha1 = "652294c14651db28fa93bd2d5ff2983a4f08c636";
      };
    };
    "core-js-2.5.5" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.5.tgz";
        sha1 = "b14dde936c640c0579a6b50cabcc132dd6127e3b";
      };
    };
    "deep-diff-0.3.8" = {
      name = "deep-diff";
      packageName = "deep-diff";
      version = "0.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-diff/-/deep-diff-0.3.8.tgz";
        sha1 = "c01de63efb0eec9798801d40c7e0dae25b582c84";
      };
    };
    "deep-equal-1.0.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz";
        sha1 = "f5d260292b660e084eff4cdbc9f08ad3247448b5";
      };
    };
    "dom-helpers-3.3.1" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-3.3.1.tgz";
        sha512 = "2zcz2kln8jkdfzzpx3cinwvdp8gcvq2pm84i4d00w9z02pchp059hzmp96slidgidc6x1xz5aifp39s97y1xc6d9ji87vr7lqjvwafr";
      };
    };
    "dom-walk-0.1.1" = {
      name = "dom-walk";
      packageName = "dom-walk";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-walk/-/dom-walk-0.1.1.tgz";
        sha1 = "672226dc74c8f799ad35307df936aba11acd6018";
      };
    };
    "encoding-0.1.12" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.12.tgz";
        sha1 = "538b66f3ee62cd1ab51ec323829d1f9480c74beb";
      };
    };
    "error-stack-parser-1.3.6" = {
      name = "error-stack-parser";
      packageName = "error-stack-parser";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-stack-parser/-/error-stack-parser-1.3.6.tgz";
        sha1 = "e0e73b93e417138d1cd7c0b746b1a4a14854c292";
      };
    };
    "es6-error-4.1.1" = {
      name = "es6-error";
      packageName = "es6-error";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-error/-/es6-error-4.1.1.tgz";
        sha512 = "1b98y4j9fy6c2wm7ys3csnyfg8cn40sy2g958i45fdh5bnx1lkl19d4508aldabga5rm1q5hzxq68yjdyb8n6qxb8925x1b2cbzwvsj";
      };
    };
    "fbjs-0.8.16" = {
      name = "fbjs";
      packageName = "fbjs";
      version = "0.8.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/fbjs/-/fbjs-0.8.16.tgz";
        sha1 = "5e67432f550dc41b572bf55847b8aca64e5337db";
      };
    };
    "global-4.3.2" = {
      name = "global";
      packageName = "global";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/global/-/global-4.3.2.tgz";
        sha1 = "e76989268a6c74c38908b1305b10fc0e394e9d0f";
      };
    };
    "hoist-non-react-statics-2.5.0" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-2.5.0.tgz";
        sha512 = "3bvgj9sbamk2kv7p7s0ham8apqqpksjnkrb61h5kd5hbsl6hzydqibk4m7sljgfmax9w6ayr4cqz79az0d25nsis927pmnkq1g7l6g8";
      };
    };
    "iconv-lite-0.4.21" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.21.tgz";
        sha512 = "0myjcmxx7dn5liikg8d2zgwb433sk761dfxwwnszyam16rzv5dzva352jrvav7cnambn0ha8fzh6g6xhdhxsd20l5v1p65r6vvmazhj";
      };
    };
    "invariant-2.2.4" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
        sha512 = "0sa0bflh46zr7zqdifqk3a48bmqlmpikrnmwvgz8nx6979piw2m92qrn1g5xnpjzxn864y2jq3gl84jkws2dad3mlwr6s3fa10my4m6";
      };
    };
    "is-promise-2.1.0" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz";
        sha1 = "79a2a9ece7f096e80f36d2b2f3bc16c1ff4bf3fa";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "isomorphic-fetch-2.2.1" = {
      name = "isomorphic-fetch";
      packageName = "isomorphic-fetch";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-2.2.1.tgz";
        sha1 = "611ae1acf14f5e81f729507472819fe9733558a9";
      };
    };
    "js-tokens-3.0.2" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz";
        sha1 = "9866df395102130e38f7f996bceb65443209c25b";
      };
    };
    "lodash-4.17.10" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz";
        sha512 = "1ba5b80jjzwrh9fbdk5ywv8sic0dynij21wgrfxsfjzwvwd7x1n6azdhdc0vjdxqmcpm0mhshd1k7n2ascxpz00z3p8a3k97mwg1s2i";
      };
    };
    "lodash-es-4.17.10" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.10.tgz";
        sha512 = "137qra8w93l5rkxr652qxlbmdzfrafp0xxzcx8s3cl1ilsgy9y35x0xlr3f50a68jmbvsccghcd6zbdzk1d42k4fa9q2qdiz5h0bsw9";
      };
    };
    "lodash.debounce-4.0.8" = {
      name = "lodash.debounce";
      packageName = "lodash.debounce";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.debounce/-/lodash.debounce-4.0.8.tgz";
        sha1 = "82d79bff30a67c4005ffd5e2515300ad9ca4d7af";
      };
    };
    "loose-envify-1.3.1" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.3.1.tgz";
        sha1 = "d1a8ad33fa9ce0e713d65fdd0ac8b748d478c848";
      };
    };
    "min-document-2.19.0" = {
      name = "min-document";
      packageName = "min-document";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/min-document/-/min-document-2.19.0.tgz";
        sha1 = "7bd282e3f5842ed295bb748cdd9f1ffa2c824685";
      };
    };
    "node-fetch-1.7.3" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-1.7.3.tgz";
        sha512 = "0lz5m15w7qaks0a0s3dm0crsjrsd123dy00pn6qwcp50zfjykxkp22i5ymh6smlc0ags38nmdxlxw9yyq509azlv8kcdvdiq857h5in";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "process-0.5.2" = {
      name = "process";
      packageName = "process";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.5.2.tgz";
        sha1 = "1638d8a8e34c2f440a91db95ab9aeb677fc185cf";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "17cn4nns2nxh9r0pdiqsqx3fpvaa82c1mhcr8r84k2a9hkpb0mj4bxzfbg3l9iy74yn9hj6mh2gsddsi3v939a1zp7ycbzqkxfm12cy";
      };
    };
    "prop-types-15.6.0" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.6.0.tgz";
        sha1 = "ceaf083022fc46b4a35f69e13ef75aed0d639856";
      };
    };
    "prop-types-15.6.1" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.6.1.tgz";
        sha512 = "28vp2j7wpa97ygi4clflilfs8wj8qsz1x3fismsqx293a9cvpyc20k4pbrppyn7y6hks0dp3mn0wmj5q3y1y3i5k7ra5ssqimnkprz1";
      };
    };
    "ramda-0.25.0" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.25.0.tgz";
        sha512 = "1qixam46hr8jsw2f4g0rvhn8jf493dpjqhi65ggacz83ndqwnal1m8kiy18d3ak9x4lapcjb1fvrx18zj26jfhlxp51vhsghnnmyyhr";
      };
    };
    "ramda-adjunct-2.7.0" = {
      name = "ramda-adjunct";
      packageName = "ramda-adjunct";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda-adjunct/-/ramda-adjunct-2.7.0.tgz";
        sha512 = "3f18ki2w49p3rqbp1wqd289pwcins48fp8rl33khfbj04wcqp34dklc0si5r5d320gvzywcj6l8nfm28wbf25h7xxqbf8fhwil2d341";
      };
    };
    "ramda-asserters-0.0.12" = {
      name = "ramda-asserters";
      packageName = "ramda-asserters";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda-asserters/-/ramda-asserters-0.0.12.tgz";
        sha512 = "3325iznfladjbmjnxvrhq702wlk8bch4yrdwkh9ljcs0mis5xnmzwmgkhpg36y7d5qfsj89b5krrawagq41iil3bgs0pnjmivb4g3hz";
      };
    };
    "react-16.3.2" = {
      name = "react";
      packageName = "react";
      version = "16.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.3.2.tgz";
        sha512 = "2bghgh4i3nn37khiycfn84cwyygh9wyzgkbny9n6qapr02z44j6m3wgl3di96cf8hm1s61zghwd7ch7v05slylq2bf0v2aw91v8z4d3";
      };
    };
    "react-deep-force-update-2.1.1" = {
      name = "react-deep-force-update";
      packageName = "react-deep-force-update";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-deep-force-update/-/react-deep-force-update-2.1.1.tgz";
        sha1 = "8ea4263cd6455a050b37445b3f08fd839d86e909";
      };
    };
    "react-dom-16.3.2" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.3.2.tgz";
        sha512 = "0l70q95rcc58vsr4fb1qw8q7ixc6az732zzxa1v26p8qkp603ghnpfhwpfbc6zcbi3ldcpgj08i2r95y1g1pq7yrxmw77fqgjiy9hrh";
      };
    };
    "react-hot-loader-3.1.3" = {
      name = "react-hot-loader";
      packageName = "react-hot-loader";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-hot-loader/-/react-hot-loader-3.1.3.tgz";
        sha512 = "0qjws65lcaav9chzdnhcks2v48v3ncacq7k25jzj4ydv5khf152qzjfn1xbgb0nrlbg51hfpa51ja09g8vy7n4k6w31mbr2pxzxkfbp";
      };
    };
    "react-image-1.3.1" = {
      name = "react-image";
      packageName = "react-image";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-image/-/react-image-1.3.1.tgz";
        sha512 = "0a7pklsfpywa6c8kjvvly65njzk0826qvhij0j549s5yj1ixp1pcfxnqawlx9x2l39x4j06px23ivbw0dj88f77kggpqrzhj7820z6d";
      };
    };
    "react-proxy-3.0.0-alpha.1" = {
      name = "react-proxy";
      packageName = "react-proxy";
      version = "3.0.0-alpha.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-proxy/-/react-proxy-3.0.0-alpha.1.tgz";
        sha1 = "4400426bcfa80caa6724c7755695315209fa4b07";
      };
    };
    "react-redux-5.0.7" = {
      name = "react-redux";
      packageName = "react-redux";
      version = "5.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-redux/-/react-redux-5.0.7.tgz";
        sha512 = "231jvmg1dgkp31sfl0czszkz77sag822nlcznpmh28cgzk3r3c8rkfcwdyihv2d5a9mqajinn999fknbcq5pripr9h06xk1bq8kqlp5";
      };
    };
    "react-transition-group-2.3.1" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-2.3.1.tgz";
        sha512 = "24mkggwklf2sjcy6w9xd7qy3ywmvwzcy363w70jnyx2nmf8s2ndgb5f0m4jky3c9m3gd5ksdg35sydzrq4qddaznzbahj450cn3zvl6";
      };
    };
    "recompose-0.26.0" = {
      name = "recompose";
      packageName = "recompose";
      version = "0.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/recompose/-/recompose-0.26.0.tgz";
        sha512 = "2i5j5zgam6qv6x440q52xyfjciy801jx1lmdl3nk5372nnjrkfvacndmmd2swmfzlg0ns98lnfn16g33hvwrzidpxwn7ljf7gmsw0rb";
      };
    };
    "redbox-react-1.6.0" = {
      name = "redbox-react";
      packageName = "redbox-react";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redbox-react/-/redbox-react-1.6.0.tgz";
        sha512 = "2k84imq6xq3zqj1hym9nf9s4sj1j6apx62f0i5mjgc84zyzjbjmcdmxrdvf5ylsppwniqc1mqd5w8dkfybiw2lnly75rqqiwvjwrf4q";
      };
    };
    "redux-3.7.2" = {
      name = "redux";
      packageName = "redux";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux/-/redux-3.7.2.tgz";
        sha512 = "3wb0gl46i4d7zr5bdm38g1a7a5j179ww8wa22wy3z3vknvpipddh1ba2w7cfkirqjg2jc69dxjhcy02vcyr4hcl3m3qx15mv9zsgnm4";
      };
    };
    "redux-form-7.3.0" = {
      name = "redux-form";
      packageName = "redux-form";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-form/-/redux-form-7.3.0.tgz";
        sha512 = "29p6y1zqn1f04a9w7cz2k70jcqxz50ffm219h41c7rbaq19y73gp1nnwn3y8phllj9pm81g4b2lb1ks3sqxv898y1jnw6qm3fqm3ijr";
      };
    };
    "redux-form-material-ui-5.0.0-beta.2" = {
      name = "redux-form-material-ui";
      packageName = "redux-form-material-ui";
      version = "5.0.0-beta.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-form-material-ui/-/redux-form-material-ui-5.0.0-beta.2.tgz";
        sha1 = "4a9186d0a6216fbb5871b07156fb0e7f591fb3e8";
      };
    };
    "redux-form-validators-2.4.3" = {
      name = "redux-form-validators";
      packageName = "redux-form-validators";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-form-validators/-/redux-form-validators-2.4.3.tgz";
        sha512 = "0fvcchs6fh4gmrydi5im20c4143p2kiqp4yp0sbcv5kb68d2qzv5xdc1xs9l7hbkll5cc071yazzicc24wa7qylhskw65276nlwvqjs";
      };
    };
    "redux-logger-git+https://github.com/srghma/redux-logger.git#ed1acad95159150c60542043e4bd19b8bb30c18a" = {
      name = "redux-logger";
      packageName = "redux-logger";
      version = "3.0.6";
      src = fetchgit {
        url = "https://github.com/srghma/redux-logger.git";
        rev = "ed1acad95159150c60542043e4bd19b8bb30c18a";
        sha256 = "2dc31e85aca873d2bc30cafb937d588ac4f19e5309c928046bfd4a92acf690dc";
      };
    };
    "redux-observable-0.17.0" = {
      name = "redux-observable";
      packageName = "redux-observable";
      version = "0.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-observable/-/redux-observable-0.17.0.tgz";
        sha512 = "1sda9hpjxqlwlqqvkfn3bfs67lyqp2bq2av5a5yxn8mwqjvrx19kaqdgy8fh1iivkkrc36k0h71h0mxxjpl0r0h875d432xmks6am4x";
      };
    };
    "regenerator-runtime-0.11.1" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz";
        sha512 = "03d4l8l8cyywh93wf5vw84lq56jh1b1d7jll4ny4z060j9hvx7w5q3q0b8q227jm93749k1c9h86r2pz0bm2xq5vp14g3r2kbvqc2rj";
      };
    };
    "reselect-3.0.1" = {
      name = "reselect";
      packageName = "reselect";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/reselect/-/reselect-3.0.1.tgz";
        sha1 = "efdaa98ea7451324d092b2b2163a6a1d7a9a2147";
      };
    };
    "reset-css-2.2.1" = {
      name = "reset-css";
      packageName = "reset-css";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/reset-css/-/reset-css-2.2.1.tgz";
        sha1 = "fe3204c0c4831979fbb4967c90a992f0164635ed";
      };
    };
    "rxjs-5.5.10" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "5.5.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-5.5.10.tgz";
        sha512 = "3lc28jznaclc3qcipvf29dnfa11m4xdzyr4gkas29pgp0s4c44f8cyzsxyfwkqzqa8k06q7j7hl5wwyy671d8gdkwl9j76lh2cf4629";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "2v99f22kh56y72d3s8wrgdvf5n10ry40dh3fwnsxr4d5rfvxdfxfmc3qyqkscnj4f8799jy9bpg6cm21x2d811dr9ib83wjrlmkg6k1";
      };
    };
    "setimmediate-1.0.5" = {
      name = "setimmediate";
      packageName = "setimmediate";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz";
        sha1 = "290cbb232e306942d7d7ea9b83732ab7856f8285";
      };
    };
    "source-map-0.5.6" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz";
        sha1 = "75ce38f52bf0733c5a7f0c118d81334a2bb5f412";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "3p7hw8p69ikj5mwapmqkacsjnbvdfk5ylyamjg9x5izkl717xvzj0vk3fnmx1n4pf54h5rs7r8ig5kk4jv4ycqqj0hv75cnx6k1lf2j";
      };
    };
    "sourcemapped-stacktrace-1.1.8" = {
      name = "sourcemapped-stacktrace";
      packageName = "sourcemapped-stacktrace";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemapped-stacktrace/-/sourcemapped-stacktrace-1.1.8.tgz";
        sha512 = "0z3m2x16c37g5a0xzkm1hsk7fh1h8vjga7v45l8brhc36qw21yfxm8d0as4mdhahmbna5r45yskpkymm32alxd4jmzvjf4hn4inhi9s";
      };
    };
    "stackframe-0.3.1" = {
      name = "stackframe";
      packageName = "stackframe";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stackframe/-/stackframe-0.3.1.tgz";
        sha1 = "33aa84f1177a5548c8935533cbfeb3420975f5a4";
      };
    };
    "symbol-observable-1.0.1" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.0.1.tgz";
        sha1 = "8340fc4702c3122df5d22288f88283f513d3fdd4";
      };
    };
    "symbol-observable-1.2.0" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.2.0.tgz";
        sha512 = "1fxqjwdn747lxzkxrwhbw8arc9czdig47izx5hnzk22z8k7rnw00q8vcpy8v7a3xyamavwgg4mvjkpn2ihjiyjxjnhx2ihiryf39pbv";
      };
    };
    "ua-parser-js-0.7.17" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.17.tgz";
        sha512 = "39ac4xrr9v9ya7rbn5cz8dss5j3s36yhpj9qrhfxxqzgy1vljns0qfyv7d76lqgdgdbfbrd91kb5x7jlg0fw2r4f3kml0v8xmv545xr";
      };
    };
    "whatwg-fetch-2.0.4" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-2.0.4.tgz";
        sha512 = "2g4p2ymmww4wm7cf86xwpb0dndwlxk1gg3brsrj892a4z593h25hyhqv0rmv4hzz4zxv3smmaflsnhilakfpr6y8f2gf3sfd8ckbi3m";
      };
    };
  };
  args = {
    name = "_at_ll2a_slash_extension";
    packageName = "@ll2a/extension";
    version = "0.0.1";
    src = ./..;
    dependencies = [
      sources."asap-2.0.6"
      sources."babel-runtime-6.26.0"
      sources."change-emitter-0.1.6"
      sources."chrome-promise-2.2.2"
      sources."core-js-2.5.5"
      sources."deep-diff-0.3.8"
      sources."deep-equal-1.0.1"
      sources."dom-helpers-3.3.1"
      sources."dom-walk-0.1.1"
      sources."encoding-0.1.12"
      sources."error-stack-parser-1.3.6"
      sources."es6-error-4.1.1"
      sources."fbjs-0.8.16"
      sources."global-4.3.2"
      sources."hoist-non-react-statics-2.5.0"
      sources."iconv-lite-0.4.21"
      sources."invariant-2.2.4"
      sources."is-promise-2.1.0"
      sources."is-stream-1.1.0"
      sources."isomorphic-fetch-2.2.1"
      sources."js-tokens-3.0.2"
      sources."lodash-4.17.10"
      sources."lodash-es-4.17.10"
      sources."lodash.debounce-4.0.8"
      sources."loose-envify-1.3.1"
      sources."min-document-2.19.0"
      sources."node-fetch-1.7.3"
      sources."object-assign-4.1.1"
      sources."process-0.5.2"
      sources."promise-7.3.1"
      (sources."prop-types-15.6.1" // {
        dependencies = [
          sources."core-js-1.2.7"
        ];
      })
      sources."ramda-0.25.0"
      sources."ramda-adjunct-2.7.0"
      sources."ramda-asserters-0.0.12"
      sources."react-16.3.2"
      sources."react-deep-force-update-2.1.1"
      sources."react-dom-16.3.2"
      sources."react-hot-loader-3.1.3"
      (sources."react-image-1.3.1" // {
        dependencies = [
          sources."prop-types-15.6.0"
        ];
      })
      sources."react-proxy-3.0.0-alpha.1"
      sources."react-redux-5.0.7"
      sources."react-transition-group-2.3.1"
      sources."recompose-0.26.0"
      (sources."redbox-react-1.6.0" // {
        dependencies = [
          sources."source-map-0.5.6"
        ];
      })
      sources."redux-3.7.2"
      sources."redux-form-7.3.0"
      sources."redux-form-material-ui-5.0.0-beta.2"
      sources."redux-form-validators-2.4.3"
      sources."redux-logger-git+https://github.com/srghma/redux-logger.git#ed1acad95159150c60542043e4bd19b8bb30c18a"
      sources."redux-observable-0.17.0"
      sources."regenerator-runtime-0.11.1"
      sources."reselect-3.0.1"
      sources."reset-css-2.2.1"
      (sources."rxjs-5.5.10" // {
        dependencies = [
          sources."symbol-observable-1.0.1"
        ];
      })
      sources."safer-buffer-2.1.2"
      sources."setimmediate-1.0.5"
      sources."source-map-0.6.1"
      sources."sourcemapped-stacktrace-1.1.8"
      sources."stackframe-0.3.1"
      sources."symbol-observable-1.2.0"
      sources."ua-parser-js-0.7.17"
      sources."whatwg-fetch-2.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "its like lingualeo extension, but better";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}