{ buildNodePackage, nodePackages, pkgs }:
buildNodePackage {
    name = "file-type";
    version = "4.4.0";
    src = pkgs.fetchurl {
      url = "https://registry.npmjs.org/file-type/-/file-type-4.4.0.tgz";
      sha1 = "1b600e5fca1fbdc6e80c0a70c71c8dba5f7906c5";
    };
    deps = [];
    meta = {
      homepage = "https://github.com/sindresorhus/file-type#readme";
      description = "Detect the file type of a Buffer/Uint8Array";
      keywords = [
        "mime"
        "file"
        "type"
        "archive"
        "image"
        "img"
        "pic"
        "picture"
        "flash"
        "photo"
        "video"
        "type"
        "detect"
        "check"
        "is"
        "exif"
        "exe"
        "binary"
        "buffer"
        "uint8array"
        "jpg"
        "png"
        "gif"
        "webp"
        "flif"
        "cr2"
        "tif"
        "bmp"
        "jxr"
        "psd"
        "zip"
        "tar"
        "rar"
        "gz"
        "bz2"
        "7z"
        "dmg"
        "mp4"
        "m4v"
        "mid"
        "mkv"
        "webm"
        "mov"
        "avi"
        "mpg"
        "mp3"
        "m4a"
        "ogg"
        "opus"
        "flac"
        "wav"
        "amr"
        "pdf"
        "epub"
        "exe"
        "swf"
        "rtf"
        "woff"
        "woff2"
        "eot"
        "ttf"
        "otf"
        "ico"
        "flv"
        "ps"
        "xz"
        "sqlite"
        "xpi"
        "cab"
        "deb"
        "ar"
        "rpm"
        "Z"
        "lz"
        "msi"
        "mxf"
        "wasm"
        "webassembly"
        "blend"
      ];
    };
  }
